
package it.mds.sdk.connettoremds.gaf.webservices.port;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "GAFWSService", targetNamespace = "http://webservices.gaf.mds.com", wsdlLocation = "http://localhost:9080/GafWebServices/services/GAFWS?wsdl")
public class GAFWSService
        extends Service
{

    private final static URL GAFWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GAFWSSERVICE_EXCEPTION;
    private final static QName GAFWSSERVICE_QNAME = new QName("http://webservices.gaf.mds.com", "GAFWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/GafWebServices/services/GAFWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GAFWSSERVICE_WSDL_LOCATION = url;
        GAFWSSERVICE_EXCEPTION = e;
    }

    public GAFWSService() {
        super(__getWsdlLocation(), GAFWSSERVICE_QNAME);
    }

    public GAFWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GAFWSSERVICE_QNAME, features);
    }

    public GAFWSService(URL wsdlLocation) {
        super(wsdlLocation, GAFWSSERVICE_QNAME);
    }

    public GAFWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GAFWSSERVICE_QNAME, features);
    }

    public GAFWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GAFWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GAFWS
     */
    @WebEndpoint(name = "GAFWS")
    public GAFWS getGAFWS() {
        return super.getPort(new QName("http://webservices.gaf.mds.com", "GAFWS"), GAFWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GAFWS
     */
    @WebEndpoint(name = "GAFWS")
    public GAFWS getGAFWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.gaf.mds.com", "GAFWS"), GAFWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GAFWSSERVICE_EXCEPTION!= null) {
            throw GAFWSSERVICE_EXCEPTION;
        }
        return GAFWSSERVICE_WSDL_LOCATION;
    }

}
