
package it.mds.sdk.connettoremds.dpm.webservice.port;

import it.mds.sdk.connettoremds.dpm.webservice.bean.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DpmPort", targetNamespace = "http://be.dpm.mds.it")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DpmPort {


    /**
     * 
     * @param dpmVerificaStatoXmlRequest
     * @return
     *     returns com.dpm.ws.client.DpmVerificaStatoXmlResponse
     */
    @WebMethod
    @WebResult(name = "dpmVerificaStatoXmlResponse", targetNamespace = "http://be.dpm.mds.it", partName = "dpmVerificaStatoXmlResponse")
    public DpmVerificaStatoXmlResponse dpmVerificaStatoXml(
        @WebParam(name = "dpmVerificaStatoXmlRequest", targetNamespace = "http://be.dpm.mds.it", partName = "dpmVerificaStatoXmlRequest")
        DpmVerificaStatoXmlRequest dpmVerificaStatoXmlRequest);

    /**
     * 
     * @param dpmInvioXmlRequest
     * @return
     *     returns com.dpm.ws.client.DpmInvioXmlResponse
     */
    @WebMethod
    @WebResult(name = "dpmInvioXmlResponse", targetNamespace = "http://be.dpm.mds.it", partName = "dpmInvioXmlResponse")
    public DpmInvioXmlResponse dpmInvioXml(
        @WebParam(name = "dpmInvioXmlRequest", targetNamespace = "http://be.dpm.mds.it", partName = "dpmInvioXmlRequest")
        DpmInvioXmlRequest dpmInvioXmlRequest);

}
