
package it.mds.sdk.connettoremds.dpm.webservice.port;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DpmPortService", targetNamespace = "http://be.dpm.mds.it", wsdlLocation = "http://localhost:9080/dpm-ws/DPMWS?wsdl")
public class DpmPortService
    extends Service
{

    private final static URL DPMPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException DPMPORTSERVICE_EXCEPTION;
    private final static QName DPMPORTSERVICE_QNAME = new QName("http://be.dpm.mds.it", "DpmPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/dpm-ws/DPMWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DPMPORTSERVICE_WSDL_LOCATION = url;
        DPMPORTSERVICE_EXCEPTION = e;
    }

    public DpmPortService() {
        super(__getWsdlLocation(), DPMPORTSERVICE_QNAME);
    }

    public DpmPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DPMPORTSERVICE_QNAME, features);
    }

    public DpmPortService(URL wsdlLocation) {
        super(wsdlLocation, DPMPORTSERVICE_QNAME);
    }

    public DpmPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DPMPORTSERVICE_QNAME, features);
    }

    public DpmPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DpmPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DpmPort
     */
    @WebEndpoint(name = "DpmPortSoap11")
    public DpmPort getDpmPortSoap11() {
        return super.getPort(new QName("http://be.dpm.mds.it", "DpmPortSoap11"), DpmPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DpmPort
     */
    @WebEndpoint(name = "DpmPortSoap11")
    public DpmPort getDpmPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://be.dpm.mds.it", "DpmPortSoap11"), DpmPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DPMPORTSERVICE_EXCEPTION!= null) {
            throw DPMPORTSERVICE_EXCEPTION;
        }
        return DPMPORTSERVICE_WSDL_LOCATION;
    }

}
